name: Secret Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret-scanning:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Infisical CLI
        run: |
          curl -1sLf \
          'https://artifacts-cli.infisical.com/setup.deb.sh' \
          | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical

      - name: Run secret scanning
        run: |
          infisical scan --verbose --report-path secret-scanning-report.json

      - name: Print scan results
        if: always()
        run: |
          cat secret-scanning-report.json
